version: '3.7'

services:

  mysql:
    image: mysql:8.0
    restart: on-failure
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--socket=/tmp/mysql.sock']
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_HOST=%
    ports:
      - "5306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    container_name: student_dashboard_mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ}
    command: bash -c "./start.sh"
    volumes:
      - .:/code
      # Use the container's node_modules and static folder (don't override)
      - /code/node_modules/
      - /code/static/
      - ${HOME}/mylasecrets:/secrets
    ports:
      - "5001:5000"
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - mysql
      - webpack_watcher
    env_file:
      - .env
    environment:
      - GUNICORN_RELOAD=True
      # port in use when the application is running on localhost
      - LOCALHOST_PORT=5001
    container_name: student_dashboard
  webpack_watcher:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-webpack
    command: sh -c "tar zxvf node_modules/all_symlinks.tgz && npm run watch"
    volumes:
      - .:/usr/src/app
      # use the container's node_modules folder (don't override)
      - /usr/src/app/node_modules/
    container_name: webpack_watcher
