name: Docker image CI

on:
  push:
    branches: ['master']
  
env:
  IMAGE_TAG: latest
  REPO_URL: ${{ github.repository }}
    
jobs:
  build:
    if: github.repository_owner == 'tl-its-umich-edu'
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout code 
        uses: actions/checkout@v3
    
      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV
      
      - name: build Docker image
        run: |
          docker build . --tag ghcr.io/${{ env.REPO_URL }}:${{ env.IMAGE_TAG }}-${BRANCH_NAME}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.REPO_URL }}:${{ env.IMAGE_TAG }}-${BRANCH_NAME}
      
